### PR TITLE
Update environment.yml

### PR DESCRIPTION
**Pull request by grst**
Update Docker container to make tests in #6 pass.

### CODE REVIEW

**Review by ggabernet — APPROVED** [review]
Looks good, thanks!

**Review by apeltzer — APPROVED** [review]

**Comment by apeltzer** [comment]
Guess the linting will atm fail anyways, so just merge #7

**Comment by grst** [comment]
thx! 

So the `smartseq2:dev` container should now update itself, right?

**Comment by ggabernet** [comment]
yes, it built successfully 33 min ago: 
 https://hub.docker.com/r/nfcore/smartseq2/builds

**Pull request merged**
