### PR TITLE
Getting ready for initial release

### PR DESCRIPTION
**Pull request by grst**
## PR checklist
- [ ] ~Ensure the test suite passes (`nextflow run . -profile test,docker`).~
The tests don't pass but this is due to the Docker container needs to be rebuilt (which should happen automatically, once this is merged) 

- [x] Make sure your code lints (`nf-core lint .`).

### CODE REVIEW

**Comment by grst** [comment]
@nf-core/all, can someone please merge this into develop, s.t. we can continue with the Review of the pseudo PR for intial release (#4)? 

Since it will be discussed in the pseudo PR anyway a review of this PR should not be necessary at this stage. 

thx, 
Gregor

**Comment by ggabernet** [comment]
Hi @grst ,

in these cases where the container needs to be built we usually make a separate PR just with the changes in the `Dockerfile` / `environment.yml`. Do you think that would be possible here?

Otherwise we might be introducing bugs that can't be tracked as the tests don't pass.

**Comment by abhi18av** [comment]
I agree with @ggabernet , also since many of the tests are failing as well it doesn't feel right to force push the releases this way. 

What do you think should be the minimal change to make the tests happy?

**Comment by grst** [comment]
I agree in principle, the point here is that this pipeline hasn't been released yet at all and is currently under initial review in #4. 

But probably it's still the cleaner approach. I'll make a separate PR with just the `environment.yml`.

**Comment by grst** [comment]
See #7

**Comment by apeltzer** [comment]
Merged just #7 to get DockerHub to build your container once more - once that is finished, we can retrigger the tests here and you can continue with proper tests running :-)

**Comment by grst** [comment]
Ok, this passes now. 

The pending, required "test" does not exist any more -- I changed to a test-matrix which caused the tests to be renamed.

**Review by ggabernet — APPROVED** [review]
It looks good to me :)

**Comment by ggabernet** [comment]
I've removed that test from the required tests to pass and added the new ones, so now it can be merged

**Comment by grst** [comment]
Perfect, thanks!

**Comment by abhi18av** [comment]
@grst, thanks for being so responsive on this 👍

**Pull request merged**
